#!/usr/bin/env python3

import argparse
import json
import re
import requests
import pandas as pd
from io import BytesIO

parser = argparse.ArgumentParser(description="Generate timetable JSON from XLS")
parser.add_argument("-t", "--timetable-url", required=True, type=str, help="Public url for xls file")
parser.add_argument("-d", "--debug", action="store_true", help="Enable verbose logging")
parser.add_argument("-e", "--even-sem", action="store_true", help="Is this even sem")
args = parser.parse_args()

STATIC_EVEN_SEM=[
    "btechsem2.json",
    "btechsem4.json",
    "btechsem6.json",
    "btechsem8.json",
    "mtechsem2.json",
    "mtechsem4.json"
]

STATIC_ODD_SEM = [
    "btechsem1.json",
    "btechsem3.json",
    "btechsem5.json",
    "btechsem7.json",
    "mtechsem1.json",
    "mtechsem3.json",
]

DAY_ROW = {0: (1, 17), 1: (17, 33), 2: (33, 49), 3: (49, 65), 4: (65, 81), 5: (81, 97)}

if args.debug:
    print("Downloading XLS file...")

response = requests.get(args.timetable_url, timeout=30)
response.raise_for_status()

xls = pd.ExcelFile(BytesIO(response.content), engine="xlrd")
sheet_names = xls.sheet_names

if args.debug:
    print("Sheets found:", sheet_names)

# skip first sheet (teachers timetable)
target_sheets = sheet_names[1:]

dfs = pd.read_excel(xls, sheet_name=target_sheets)

for idx, (sheet_name, df) in enumerate(dfs.items()):
    if args.debug:
        print(f"Processing sheet: {sheet_name}")
        print("Shape:", df.shape)

    output = []

    for day, (start, end) in DAY_ROW.items():
        for time_col in range(1, 10):

            slot_series = df.iloc[start:end, time_col]
            data_list = slot_series.dropna().astype(str).str.strip().tolist()
            output.append({
                "day": day,
                "time": time_col-1,
                "data": data_list
            })
    filename="unknown"
    if args.even_sem :
        filename=STATIC_EVEN_SEM[idx]
    else :
        filename=STATIC_ODD_SEM[idx]

    if args.debug:
        print(f"Writing {filename} ({len(output)} entries)")

    with open(filename, "w", encoding="utf-8") as f:
        json.dump(output, f, ensure_ascii=False, indent=2)

